export const STORE_TYPES = {
  SEVEN_ELEVEN: "STR-7ELV",
  FAMILY_MART: "STR-FAMI",
  MINI_STOP: "STR-MINI",
  GS25: "STR-GS25",
  BSM: "STR-BSM",
  CIRCLE_K: "STR-CCK",
  KINGFOOD: "STR-KING",
  // Add other store types as needed
};

export const FILE_TYPES = {
  CHECKLIST: "checklist",
  RAW_DATA: "rawData",
  PROMOTION: "promotion",
  RAW_PROMOTION: "rawPromotion",
};

export const CHECK_TYPES = {
  DAILY: "daily",
  SCORING: "scoring",
  PROMOTION: "promotion",
};

export const CHECKLIST_HEADERS = [
  "No.",
  "PH3_Desc",
  "PS CATEGORY",
  "VARIANT",
  "Old code",
  "New code",
  "Item Code",
  "PRODUCT NAME",
  "TÊN HÀNG ESS & AUDIT",
  "START DATE",
  "END DATE",
  "PPT NOTE FOR AUDIT",
  "Ngày Bắt Đầu Linh Động Đo Hàng Cũ & Mới",
  "Ngày Kết Thúc Linh Động Đo Hàng Cũ & Mới",
  "Ngày review SKU relaunch",
  "ESS DP CODE",
  "DP NAME",
  "BRAND",
  "PACKSIZE",
  "BARCODE",
  "Length",
  "Height",
  "Unit of Dimension",
  "Specices_SOS",
  "Note relaunch",
  "Note for relaunch (audit)",
  "NOTE",
  "CAT",
  "Store Cover",
];

export const RAW_DATA_HEADERS = [
  "Report of month",
  "Loại",
  "Date",
  "Time",
  "PHASE",
  "Store ID - Unilever",
  "Store_name",
  "TYPESTORE",
  "Customer ID",
  "Customer",
  "Supervisor",
  "PS Category ID",
  "PS Category",
  "Product_id",
  "Audit status",
  "Product_name",
  "Vị trí",
  "Target",
  "Stock",
  "VOID (0/1/Blank)",
  "OSA (1/0)",
  "Lý do",
  "Comment",
  "Reject (1/0)",
  "Lý do Reject",
  "Team dự án Revise",
  "Team dự án phản hồi",
  "Final Reject (1/0)",
  "AUDIT",
  "Report of Month",
  "Loại",
  "Date",
  "Time",
  "Phase",
  "Store ID - Unilever",
  "Store name",
  "TYPESTORE",
  "Customer ID",
  "Customer",
  "Supervisor",
  "PS Category ID",
  "PS Category",
  "Product ID",
  "Product Name",
  "Vị trí",
  "Target",
  "Stock",
  "Void (0/1/Blank)",
  "OSA (0/1)",
  "Predefined Note",
  "Comment",
  "Reject (0/1)",
  "Lí do reject",
  "Team dự án revise",
  "Team dự án phản hồi",
  "Final reject",
  "Region",
  "Auditor",
  "Auditor Code",
  "Allow Price Tag Adjustment",
  "Price Tag Passes After Adjustment",
  "SR Feedback",
];

export const RAW_PROMOTION_DATA_HEADERS = [
  "Report of Month",
  "Loại",
  "Date",
  "Time",
  "Phase",
  "Store ID - Unilever",
  "Store name",
  "TYPESTORE",
  "Customer ID",
  "Customer",
  "Supervisor",
  "PS Category ID",
  "PS Category",
  "Product ID",
  "Promotion ID",
  "Product Name",
  "Mechanic (Chương trình khuyến mãi)",
  "Vị trí",
  "Hiện diện sản phẩm (1/0)",
  "Nội dung khuyến mãi (1/0)",
  "Thông báo khuyến mãi (1/0)",
  "Kết quả",
  "Predefined Note",
  "Comment",
  "Reject (0/1)",
  "Lý do",
  "Team dự án revise",
  "Team dự án phản hồi",
  "Final reject",
  "Region",
  "Auditor",
  "Auditor Code",
  "SR Feedback",
  "Date",
  "Time",
  "PHASE",
  "Report of month",
  "Loại",
  "Store ID - Unilever",
  "Store_name",
  "TYPESTORE",
  "Customer ID",
  "Customer",
  "Supervisor",
  "PS Category ID",
  "PS Category",
  "Product_id",
  "PromotionID",
  "Product",
  "Mechanic (Chương trình khuyến mãi)",
  "Vị trí",
  "Hiện diện SP (1/0)",
  "Nội dung KM (1/0)",
  "Thông báo KM (1/0)",
  "PRO (1/0)",
  "Lý do",
  "Comment",
  "Reject (1/0)",
  "Lý do",
  "Team dự án Revise",
  "Team dự án phản hồi",
  "Final Reject",
  "SR không đồng ý",
  "Nội dung phản hồi",
  "AH phản hồi",
  "AUDIT",
  "Audit status",
];
export const DATE_FIELDS = [
  "START DATE",
  "END DATE",
  "Ngày Bắt Đầu Linh Động Đo Hàng Cũ & Mới",
  "Ngày Kết Thúc Linh Động Đo Hàng Cũ & Mới",
  "Ngày review SKU relaunch",
];
